<a href="https://colab.research.google.com/github/rishi12jn/Predictive-analytics-Lab/blob/main/LAB3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
arr_1d = np.array([1, 2, 3, 4, 5])
print(arr_1d)

[1 2 3 4 5]


In [2]:
import numpy as np
arr1d_arange = np.arange(0, 10, 2)
print(arr1d_arange)

[0 2 4 6 8]


In [3]:
import numpy as np
arr1d_linspace = np.linspace(0, 1, 5)
print(arr1d_linspace)

[0.   0.25 0.5  0.75 1.  ]


In [4]:
import numpy as np
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_2d)

[[1 2 3]
 [4 5 6]]


In [5]:
import numpy as np
arr2d_reshaped = np.arange(6).reshape(2, 3)
print(arr2d_reshaped)

[[0 1 2]
 [3 4 5]]


In [6]:
import numpy as np
arr_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr_3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [7]:
import numpy as np
arr3d_reshaped = np.arange(8).reshape(2, 2, 2)
print(arr3d_reshaped)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [8]:
import numpy as np
arr_1d = np.array([1, 2, 3, 4, 5])
element = arr_1d[2]
print(element)

3


In [9]:
import numpy as np
arr_1d = np.array([1, 2, 3, 4, 5])
slice1d = arr_1d[1:4]
print(slice1d)

[2 3 4]


In [10]:
import numpy as np
arr_1d = np.array([1, 2, 3, 4, 5])
arr = np.arange(12)
arr_reshaped = arr.reshape(3, 4)
print(arr_reshaped)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [11]:
import numpy as np
arr_a = np.array([[1, 2], [3, 4]])
arr_b = np.array([[5, 6], [7, 8]])
arr_concat = np.concatenate((arr_a, arr_b), axis=0)
print(arr_concat)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [13]:
import numpy as np
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
shape = arr2d.shape
print(shape)

(2, 3)


In [14]:
import numpy as np
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
size = arr2d.size
print(size)

6


In [15]:
import numpy as np
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
dtype = arr2d.dtype
print(dtype)

int64


In [16]:
import numpy as np
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
ndim = arr2d.ndim
print(ndim)

2


In [17]:
import numpy as np
arr2d = np.array([[1, 2, 3], [4, 5, 6]])

arr2d = np.arange(8)
arr_reshaped = arr2d.reshape(2, 4)
print(arr_reshaped)

[[0 1 2 3]
 [4 5 6 7]]


In [19]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
arr.resize(2, 3)
print(arr)

[[1 2 3]
 [4 5 6]]


In [20]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr_flat = arr.flatten()
print(arr_flat)

[1 2 3 4 5 6]


In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv('Book1.csv')

def prob(age_col, age_value, buy_col, buy_value):
    count = 0
    total = len(age_col)
    for age, buy in zip(age_col, buy_col):
        if age == age_value and buy == buy_value:
            count += 1
    return count / total if total > 0 else 0

age = df['age']
income = df['income']
student = df['student']
credit_rating = df['credit rating']
buys_computer = df['Class: buys computer']

prob_yes = buys_computer.value_counts().get('yes', 0) / len(buys_computer)
prob_no = buys_computer.value_counts().get('no', 0) / len(buys_computer)
youth_yes_prob = prob(age, 'youth', buys_computer, 'yes')

print(f"Probability of 'youth' and 'yes': {youth_yes_prob}")
print(f"Probability of 'yes': {prob_yes}")
print(f"Probability of 'no': {prob_no}")
